version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka-rabbitmq
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  schemaregistry:
    image: confluentinc/cp-schema-registry:5.1.2
    networks:
      - broker-kafka-rabbitmq
    depends_on:
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
    ports:
      - 8085:8085

  schemaregistryui:
    image: landoop/schema-registry-ui:latest
    networks:
      - broker-kafka-rabbitmq
    depends_on:
      - schemaregistry
    environment:
      PROXY: 'true'
      SCHEMAREGISTRY_URL: schemaregistry:8085
    ports:
      - 8000:8000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka-rabbitmq
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SCHEMA_REGISTRY_URL: schemaregistry:8085

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka-rabbitmq
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      SCHEMAREGISTRY_CONNECT: schemaregistry:8085
      KAFKA_BROKERCONNECT: kafka:29092

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672


networks:
  broker-kafka-rabbitmq:
    driver: bridge